# Generated by Django 2.2.10 on 2020-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_addr', models.CharField(max_length=200)),
                ('hospital_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
